### ISSUE TITLE
Cannot see sym variables from angrgdb shell

### ISSUE THREAD

**Issue by sudo45** [andreafioraldi/angrgdb#3]
After I have marked as symbolic, I can't access to symbolic variables with angrgdb.
I want to access from script to symbolic variables because I want to set a costraint to the symbolic  variable.

Step to reproduce the bug (from this writeup: [https://ctftime.org/writeup/10342](url))

1) Download the attachment from this CTF [https://capturetheflag.withgoogle.com/#challenges/crypto-mitm](url)
2) unzip it and run: 
`gdb ./sftp`
3) set breakpoint at offset 14e1 (for example, if base address is 0x8000000, execute b *0x80014e1) and run.
4) enter "yes"
5) insert "aaaaaaaaaaaaaaa" as password
6) when gdb hit the break, excute:
`angrgdb sim $rbx, 15`
`angrgdb find  0x800145c`
`angrgdb avoid  0x800145a`
`angrgdb shell`

inside the shell:
`>>> state = m.active[0]`

Here is the error, I can't see the symbolic variable setted before:

`>>> list(state.solver.get_variables())
[]`

The list is empty.

**Comment by andreafioraldi** [comment]
The writeup is mine lol.

Thanks for the issue but this is not the correct way of using get_variables. A variable must be submitted to the tracker before using get:variables, see [here](https://github.com/angr/angr/blob/master/angr/state_plugins/solver.py#L199).

You can get all variables created with a StateManager (that is only a wrapper) you can use the `sm.symbolics` dictionary. The key are registers names of addresses, in your case the key is the value of rbx (0x7fffffffda30). The returned value is a tuple (bitvector, size) (yes size is redundant and i don't remember why).

In addition, `angrgdb sim $rbx, 15` is not a correct command, use `angrgdb sim $rbx 15` instead.

My suggestion is to not use the GDB commands when you want to use the shell, simply type `angrdbg shell` and add find/avoid addresses and symbolic values directly in python:

```python
key = sm.sim(sm["rbx"], 15) # key is solver.eval(sm["rbx"], cast_to=int)
sm[key] # get the variable in the right way
sm.symbolics[key][0] # dirty way
m.explore(find= 0x800145c, avoid= 0x800145a)
...
sm.to_dbg(m.found[0]) # write results back to gdb
```

**Comment by sudo45** [comment]
Thank you, this solved the problem!
