### ISSUE TITLE
No way of accessing angr core module to add constraints or define files.

### ISSUE THREAD

**Issue by N0fix** [andreafioraldi/angrgdb#8]
There is no easy way to use angr core module to add constraints to symbolic memory or even add a symbolic file to the state's filesystem.

**Comment by andreafioraldi** [comment]
Why not?

```
state = StateShot()
symfile.set_state(state)
state.memory.store(address, symbolic_item)
```

**Comment by N0fix** [comment]
How do you define your Symfile, and why do you map a symbolic file in memory without using angr's filesystem API?

**Comment by andreafioraldi** [comment]
state.fs to access the filesystem plugin. I donàt get the point, StateShot returns an angr state and so you can just use the angr api (as said, state.fs is the plugin) and StateManager returns a wrapper, in which you can access the angr state using statemanager.state.

**Comment by andreafioraldi** [comment]
If you read the angrdbg readme is easy. If you need more features for reason X, feel free to submit a PR.
